### ISSUE TITLE
Issues with mjx.forward when the number of actuators of the model is 1

### ISSUE THREAD

**Issue by Manchewable** [google-deepmind/mujoco#1135]
Hello, I've been playing around with mujoco version 3.0.0 and I think I've stumbled upon a bug where `mjx.forward` throws an error whenever the model only has one actuator.

Here's a minimal example that can reproduce the issue:
```
import jax
from jax import numpy as jp
import mujoco
from mujoco import mjx

CARTPOLE_XML = """
<mujoco model="cartpole">
  <option timestep="0.0083333" solver="CG" iterations="6" ls_iterations="6">
    <flag eulerdamp="disable"/>
  </option>

  <worldbody>
    <body name="cart" pos="0 0.5 0">
      <joint name="slider" type="slide" limited="true" axis="1 0 0" range="-5 5"/>
      <geom name="cart" type="box" size="0.2 0.15 0.1" mass="1"/>
      <body name="pole_1">
        <joint name="hinge_1" type="hinge" axis="0 1 0"/>
        <geom name="pole_1" type="capsule" fromto="0 0 0 0 0 1" size="0.045 .5" mass=".1"/>
      </body>
    </body>
  </worldbody>

  <actuator>
    <motor name="slide" joint="slider"/>
  </actuator>
</mujoco>
"""

if __name__ == "__main__":
    mj_model = mujoco.MjModel.from_xml_string(CARTPOLE_XML)
    mj_data = mujoco.MjData(mj_model)

    mjx_model = mjx.device_put(mj_model)
    mjx_data = mjx.device_put(mj_data)

    qpos = jp.zeros(mj_model.nq)
    qvel = jp.zeros(mj_model.nv)

    mjx_data = mjx_data.replace(qpos=qpos, qvel=qvel, ctrl=jp.zeros(mjx_model.nu))
    mjx_data = mjx.forward(mjx_model, mjx_data)
```
And this is the associating error stack trace:
```
Traceback (most recent call last):
  File "/home/mcleung/projects/mjx_test/cartpole.py", line 48, in <module>
    mjx_data = mjx.forward(mjx_model, mjx_data)
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/forward.py", line 57, in wrapper
    res = fn(*args, **kwargs)
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/forward.py", line 329, in forward
    d = _actuation(m, d)
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/forward.py", line 57, in wrapper
    res = fn(*args, **kwargs)
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/forward.py", line 154, in _actuation
    force = scan.flat(
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/scan.py", line 192, in flat
    _check_input(m, args, in_types)
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/mujoco/mjx/_src/scan.py", line 131, in _check_input
    if len(a) != size[typ]:
  File "/home/mcleung/miniconda3/envs/mjx/lib/python3.9/site-packages/jax/_src/array.py", line 256, in __len__
    raise TypeError("len() of unsized object") from err  # same as numpy error
TypeError: len() of unsized object
```

If this is not a bug, any insight as to where the problem is will be appreciated. Thanks!

**Comment by btaba** [comment]
Hi @Manchewable thanks for the report! This was fixed in 44ba099
